version: '3'
services:
  postgres:
    image: postgres:13.5
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200
    environment:
      POSTGRES_DB: FoodTracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - postgresdb:/var/lib/postgresql/data
volumes:
  postgresdb: